=== Gregorooooo02/portfolioSite/exercisesFiles/exercise5/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.example.org/plytoteka"
xmlns:cds="https://www.example.org/plytoteka"
elementFormDefault="qualified">

<xsd:element name="exercise" type="cds:exerciseType">
	<xsd:key name="id">
		<xsd:selector xpath="./cds:library/cds:disk"/>
		<xsd:field xpath="@id"/>
	</xsd:key>
	<xsd:key name="genreId">
		<xsd:selector xpath="./cds:genres/cds:genre"/>
		<xsd:field xpath="@genreId"/>
	</xsd:key>
	<xsd:key name="studentId">
		<xsd:selector xpath="./cds:students/cds:student"/>
		<xsd:field xpath="@studentId"/>
	</xsd:key>
	<xsd:keyref name="keyRefGenre" refer="cds:genreId">
		<xsd:selector xpath="./cds:library/cds:disk"/>
		<xsd:field xpath="@genreId"/>
	</xsd:keyref>
	<xsd:keyref name="keyRefStudent" refer="cds:studentId">
		<xsd:selector xpath="./cds:genres/cds:genre"/>
		<xsd:field xpath="@studentId"/>
	</xsd:keyref>
</xsd:element>

<xsd:complexType name="exerciseType">
	<xsd:sequence>
		<xsd:group ref="cds:exerciseGroup"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="headingType">
	<xsd:sequence>
		<xsd:element name="projectName" type="xsd:string"/>
		<xsd:element name="subject" type="xsd:string"/>
		<xsd:element name="author" type="xsd:string"/>
		<xsd:element name="index" type="cds:indexType"/>
		<xsd:element name="lastModified" type="xsd:date"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="indexType">
	<xsd:restriction base="xsd:string">
		<xsd:pattern value="[0-9]{6}"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="libraryType">
	<xsd:sequence>
		<xsd:element name="disk" type="cds:diskType" maxOccurs="35"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="diskType">
	<xsd:sequence>
		<xsd:group ref="cds:diskGroup"/>
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="genreId" type="xsd:string" use="required"/>
	<xsd:attribute name="favorite" type="xsd:string" use="optional"/>
</xsd:complexType>

<xsd:complexType name="studentsType">
	<xsd:sequence>
		<xsd:element name="student" type="cds:studentType" maxOccurs="10"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="studentType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="studentId" type="xsd:string" use="required"/>
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="genresType">
	<xsd:sequence>
		<xsd:element name="genre" type="cds:genreType" maxOccurs="12"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="genreType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="genreId" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Progressive Metal"/>
						<xsd:enumeration value="Alternative Metal"/>
						<xsd:enumeration value="Nu Metal"/>
						<xsd:enumeration value="Grunge"/>
						<xsd:enumeration value="Hip-Hop"/>
						<xsd:enumeration value="Indie Rock"/>
						<xsd:enumeration value="Techno"/>
						<xsd:enumeration value="Electronica"/>
						<xsd:enumeration value="Alternative Rap"/>
						<xsd:enumeration value="Phonk"/>
						<xsd:enumeration value="Post-punk"/>
						<xsd:enumeration value="Synthwave"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:simpleType name="releasedType">
	<xsd:restriction base="xsd:string">
		<xsd:pattern value="[0-3][0-9]/[0-1][0-9]/[0-9]{4}"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="lengthType">
	<xsd:restriction base="xsd:string">
		<xsd:pattern value="[0-9]{2}:[0-9]{2}|[0-9]:[0-9]{2}"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="priceType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:decimal">
			<xsd:attribute name="currency" type="xsd:string" use="required"/>
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="albumCoverType">
	<xsd:attribute name="URL" type="xsd:anyURI" use="optional"/>
</xsd:complexType>

<xsd:group name="exerciseGroup">
	<xsd:sequence>
		<xsd:element name="heading" type="cds:headingType"/>
		<xsd:element name="library" type="cds:libraryType"/>
		<xsd:element name="students" type="cds:studentsType"/>
		<xsd:element name="genres" type="cds:genresType"/>
	</xsd:sequence>
</xsd:group>

<xsd:group name="diskGroup">
	<xsd:sequence>
		<xsd:element name="author" type="xsd:string"/>
		<xsd:element name="title" type="xsd:string"/>
		<xsd:element name="released" type="xsd:string"/>
		<xsd:element name="howManySongs" type="xsd:integer"/>
		<xsd:element name="length" type="cds:lengthType"/>
		<xsd:element name="price" type="cds:priceType"/>
		<xsd:element name="ratings" type="xsd:decimal"/>
		<xsd:element name="albumCover" type="cds:albumCoverType"/>
	</xsd:sequence>
</xsd:group>

</xsd:schema>

=== Gregorooooo02/portfolioSite/exercisesFiles/exercise3/XML/exercise.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="style.css" ?>

<!--Element główny = korzeń-->
<cds:exercise
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:cds="plytoteka"
xsi:schemaLocation="plytoteka schema.xsd">
  <!--Nagłówek strony i podstawowe informacje-->
  <cds:heading>
    <cds:projectName>Płytoteka CD z różnymi gatunkami muzyki</cds:projectName>
    <cds:subject>Technologie XML</cds:subject>
    <cds:author>Grzegorz Bednarek</cds:author>
    <cds:index>242359</cds:index>
    <cds:lastModified>2022-11-06</cds:lastModified>
  </cds:heading>
    
  <cds:library text="Moja biblioteka płyt CD">
    <cds:disk diskId="D1" genreId="Progressive Metal" studentId="S3">
      <cds:author>TOOL</cds:author>
      <cds:title>10.000 Days</cds:title>
      <cds:info>
        <cds:released>28/04/2006</cds:released>
        <cds:howManySongs>11</cds:howManySongs>
        <cds:length time="75:45"/>
        <cds:price currency="PLN">62.99</cds:price>
        <cds:ratings>4.9</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://image.ceneostatic.pl/data/products/2735398/i-tool-10-000-days-cd.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D2" genreId="Alternative Metal" studentId="S5">
      <cds:author>A Perfect Circle</cds:author>
      <cds:title>Thirteenth Step</cds:title>
      <cds:info>
        <cds:released>16/09/2003</cds:released>
        <cds:howManySongs>12</cds:howManySongs>
        <cds:length time="50:36"/>
        <cds:price currency="PLN">53.99</cds:price>
        <cds:ratings>4.2</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://ecsmedia.pl/c/thirteenth-step-b-iext120253671.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D3" genreId="Nu Metal" studentId="S4">
      <cds:author>Limp Bizkit</cds:author>
      <cds:title>STILL SUCKS</cds:title>
      <cds:info>
        <cds:released>31/10/2021</cds:released>
        <cds:howManySongs>12</cds:howManySongs>
        <cds:length time="31:55"/>
        <cds:price currency="PLN">40.00</cds:price>
        <cds:ratings>4.8</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://soundrive.pl/assets/front/images/content/1fW4VGNkY1e4X3uObVdtefhF5lDqSaG7GZ2fjuAkNOmg9VpCmH0c39kL70Mu_limp-bizkit-still-sucksjpg.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D4" genreId="Grunge" studentId="S8">
      <cds:author>Pearl Jam</cds:author>
      <cds:title>Ten</cds:title>
      <cds:info>
        <cds:released>27/08/1991</cds:released>
        <cds:howManySongs>11</cds:howManySongs>
        <cds:length time="53:20"/>
        <cds:price currency="PLN">35.97</cds:price>
        <cds:ratings>4.5</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://image.ceneostatic.pl/data/products/2734314/i-pearl-jam-ten-cd.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D5" genreId="Alternative Metal" studentId="S4">
      <cds:author>Karnivool</cds:author>
      <cds:title>Themata</cds:title>
      <cds:info>
        <cds:released>07/02/2005</cds:released>
        <cds:howManySongs>12</cds:howManySongs>
        <cds:length time="48:52"/>
        <cds:price currency="PLN">30.00</cds:price>
        <cds:ratings>4.0</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://m.media-amazon.com/images/I/8173EyIhkRL.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D6" genreId="Hip-Hop" studentId="S3">
      <cds:author>Matt Large</cds:author>
      <cds:title>As real as it gets</cds:title>
      <cds:info>
        <cds:released>18/05/2018</cds:released>
        <cds:howManySongs>12</cds:howManySongs>
        <cds:length time="31:33"/>
        <cds:price currency="PLN">22.99</cds:price>
        <cds:ratings>4.5</cds:ratings>
      </cds:info>      
      <cds:albumCover URL="https://cdn.epidemicsound.com/curation-assets/commercial-release-cover-images/424/300x300.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D7" genreId="Indie Rock" studentId="S6">
      <cds:author>Low Roar</cds:author>
      <cds:title>0</cds:title>
      <cds:info>
        <cds:released>05/08/2014</cds:released>
        <cds:howManySongs>13</cds:howManySongs>
        <cds:length time="68:14"/>
        <cds:price currency="PLN">32.99</cds:price>
        <cds:ratings>4.2</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://m.media-amazon.com/images/I/71kUJ6leTCL.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D8" genreId="Grunge" studentId="S3">
      <cds:author>Nirvana</cds:author>
      <cds:title>Nevermind</cds:title>
      <cds:info>
        <cds:released>24/09/1991</cds:released>
        <cds:howManySongs>12</cds:howManySongs>
        <cds:length time="42:38"/>
        <cds:price currency="PLN">32.00</cds:price>
        <cds:ratings>4.0</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://upload.wikimedia.org/wikipedia/en/b/b7/NirvanaNevermindalbumcover.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D9" genreId="Techno" studentId="S9">
      <cds:author>The Prodigy</cds:author>
      <cds:title>The Day Is My Enemy</cds:title>
      <cds:info>
        <cds:released>30/03/2015</cds:released>
        <cds:howManySongs>15</cds:howManySongs>
        <cds:length time="56:12"/>
        <cds:price currency="PLN">45.87</cds:price>
        <cds:ratings>3.9</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://ecsmedia.pl/c/the-day-is-my-enemy-w-iext120305294.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D10" genreId="Hip-Hop" studentId="S10">
      <cds:author>Snoop Dogg</cds:author>
      <cds:title>Ego Trippin'</cds:title>
      <cds:info>
        <cds:released>11/03/2008</cds:released>
        <cds:howManySongs>24</cds:howManySongs>
        <cds:length time="77:43"/>
        <cds:price currency="PLN">72.89</cds:price>
        <cds:ratings>4.3</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://kolekcjonerrapu.pl/userdata/public/gfx/3941/Snoop-Dogg---Ego-Trippin--cover-okladka.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D11" genreId="Electronica" studentId="S1">
      <cds:author>Michal Aniol</cds:author>
      <cds:title>U</cds:title>
      <cds:info>
        <cds:released>19/02/2021</cds:released>
        <cds:howManySongs>10</cds:howManySongs>
        <cds:length time="34:27"/>
        <cds:price currency="PLN">29.99</cds:price>
        <cds:ratings>4.1</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://ecsmedia.pl/c/u-b-iext67667192.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D12" genreId="Alternative Rap" studentId="S1">
      <cds:author>CatchUp</cds:author>
      <cds:title>Jesieniarze - Single</cds:title>
      <cds:info>
        <cds:released>12/10/2020</cds:released>
        <cds:howManySongs>1</cds:howManySongs>
        <cds:length time="2:35"/>
        <cds:price currency="PLN">12.99</cds:price>
        <cds:ratings>4.7</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://images.genius.com/7dd383abb733bc4cdfb036e2163c1691.720x720x1.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D13" genreId="Alternative Rap" studentId="S1">
      <cds:author>Michal Aniol</cds:author>
      <cds:title>Bo to sie zwykle tak zaczyna - EP</cds:title>
      <cds:info>
        <cds:released>08/04/2022</cds:released>
        <cds:howManySongs>4</cds:howManySongs>
        <cds:length time="11:39"/>
        <cds:price currency="PLN">21.37</cds:price>
        <cds:ratings>4.9</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://images.genius.com/d46edce1e54ee7b87242472a4816375c.1000x1000x1.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D14" genreId="Electronica" studentId="S1">
      <cds:author>Michal Aniol</cds:author>
      <cds:title>Blisko - Single</cds:title>
      <cds:info>
        <cds:released>05/08/2020</cds:released>
        <cds:howManySongs>1</cds:howManySongs>
        <cds:length time="3:03"/>
        <cds:price currency="PLN">9.99</cds:price>
        <cds:ratings>5.0</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://images.genius.com/2f7bda4b7fd1613eaec073cd61ec2d99.640x640x1.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D15" genreId="Alternative Rap" studentId="S7">
      <cds:author>Kacperczyk</cds:author>
      <cds:title>Kryzys Wieku Wczesnego</cds:title>
      <cds:info>
        <cds:released>26/11/2021</cds:released>
        <cds:howManySongs>14</cds:howManySongs>
        <cds:length time="35:56"/>
        <cds:price currency="PLN">44.99</cds:price>
        <cds:ratings>4.6</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://ecsmedia.pl/c/kryzys-wieku-wczesnego-pl-b-iext104212093.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D16" genreId="Electronica" studentId="S7">
      <cds:author>Frank Leen</cds:author>
      <cds:title>Za dobrze by zapomniec</cds:title>
      <cds:info>
        <cds:released>09/09/2022</cds:released>
        <cds:howManySongs>1</cds:howManySongs>
        <cds:length time="2:32"/>
        <cds:price currency="PLN">7.99</cds:price>
        <cds:ratings>5.0</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://images.genius.com/f1a7457f2e1d93b10e189eb5202e8f91.1000x1000x1.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D17" genreId="Hip-Hop" studentId="S5">
      <cds:author>Eminem</cds:author>
      <cds:title>Kamikaze</cds:title>
      <cds:info>
        <cds:released>31/08/2018</cds:released>
        <cds:howManySongs>13</cds:howManySongs>
        <cds:length time="45:49"/>
        <cds:price currency="PLN">55.55</cds:price>
        <cds:ratings>4.4</cds:ratings>
      </cds:info>
      <cds:albumCover URL="https://images.genius.com/f1422cedbca472fd80dc00fa7f6e652c.1000x1000x1.jpg"/>
    </cds:disk>
    
    <cds:disk diskId="D18" genreId="Hip-Hop" studentId="S6">
      <cds:author>Eminem</cds:author>
      <cds:title>Music To Be Murdered By</cds:title>
      <cds:info>
        <cds:released>17/01/2020</cds:released>
        <cds:howManySongs>20</cds:howManySongs>
        <cds:length time="64:23"/>
